version: "2"

services:
  elasticsearch:
    image: "devpriyesh2609/bitnami-elasticsearch:latest"
    environment:
      - BITNAMI_DEBUG=true
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - "/home/ubuntu/bitnami-docker-elasticsearch/7/debian-10/data:/bitnami/elasticsearch/data"
